import palette from "./palette";
export default {
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  sizes: {
    container: "80rem",
  },
  fonts: {
    body: '"Montserrat", sans-serif',
    heading: '"Lora", serif',
    monospace: '"Menlo", monospace',
  },
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64, 96],
  fontWeights: {
    body: 400,
    heading: 700,
    bold: 600,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  colors: {
    text: palette.black,
    background: palette.white,
    surface: palette.white,
    underlay: palette.gray[2],
    primary: palette.brand,
    secondary: palette.gray[6],
    onPrimary: palette.white,
    onSecondary: palette.white,
    onBackground: palette.black,
    onSurface: palette.black,
    footerNavigationBackground: palette.gray[10],
    onFooterNavigationBackground: palette.gray[3],
    onFooterNavigationBackgroundHighlight: palette.white,
    footerCreditsBackground: palette.black,
    onFooterCreditsBackground: palette.gray[3],
    onFooterCreditsBackgroundHighlight: palette.white,
    pillarEconomicRecoveryLight: palette.orange[5],
    pillarMacroResponseLight: palette.red[5],
    pillarSocialCohesionLight: palette.purple[5],
    pillarHealthFirstLight: palette.indigo[5],
    pillarProtectPeopleLight: palette.teal[5],
    pillarEconomicRecovery: palette.orange[7],
    pillarMacroResponse: palette.red[7],
    pillarSocialCohesion: palette.purple[7],
    pillarHealthFirst: palette.indigo[7],
    pillarProtectPeople: palette.teal[7],
    pillarEconomicRecoveryDark: palette.orange[9],
    pillarMacroResponseDark: palette.red[9],
    pillarSocialCohesionDark: palette.purple[9],
    pillarHealthFirstDark: palette.indigo[9],
    pillarProtectPeopleDark: palette.teal[9],
    onPillar: palette.white,
  },
  shadows: {
    header: "0 0.1rem 0.3rem 0 rgba(0,0,0,.1)",
    card: "0 0.1rem 0.3rem 0 rgba(0,0,0,.1)",
  },
  styles: {
    root: {
      fontFamily: "body",
      lineHeight: "body",
      fontWeight: "body",
      bg: "background",
    },
    h1: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 5,
    },
    h2: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 4,
    },
    h3: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 3,
    },
    h4: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 2,
    },
    h5: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 1,
    },
    h6: {
      color: "text",
      fontFamily: "heading",
      lineHeight: "heading",
      fontWeight: "heading",
      fontSize: 0,
    },
    p: {
      color: "text",
      fontFamily: "body",
      fontWeight: "body",
      lineHeight: "body",
      maxWidth: "48rem",
    },
    a: {
      color: "primary",
    },
    pre: {
      fontFamily: "monospace",
      overflowX: "auto",
      code: {
        color: "inherit",
      },
    },
    code: {
      fontFamily: "monospace",
      fontSize: "inherit",
    },
    table: {
      width: "100%",
      borderCollapse: "separate",
      borderSpacing: 0,
    },
    th: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    td: {
      textAlign: "left",
      borderBottomStyle: "solid",
    },
    img: {
      maxWidth: "100%",
    },
  },
};
